Repository YAPP-Github/Coffice-iOS, pull requests merged in 2023-07, with the labels that each got.

#82 Feature/#74 toast view 제작
  Projects/Coffice/Sources/App/Extensions/CofficeFont+Extensions.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/ToastCore.swift
  Projects/Coffice/Sources/App/Main/ToastView.swift
  Tuist/Dependencies.swift
Labels: Feature

#84 Feature/#81 review write textview UI
  Projects/Coffice/Sources/App/Extensions/UITextView+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewTextView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/KeyboardPresentationReadable.swift
Labels: Feature

#87 Feature/#83 api client update
  Projects/Coffice/Project.swift
  Projects/Coffice/Sources/App/AppCoordinatorCore.swift
  Projects/Coffice/Sources/App/Dependencies/LoginClient.swift
  Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
  Projects/Coffice/Sources/App/Entities/Address.swift
  Projects/Coffice/Sources/App/Entities/Cafe.swift
  Projects/Coffice/Sources/App/Entities/CafeFilters.swift
  Projects/Coffice/Sources/App/Entities/CafeSearchResponse.swift
  Projects/Coffice/Sources/App/Entities/CrowdednessResponse.swift
  Projects/Coffice/Sources/App/Entities/OpeningHourResponse.swift
  Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
  Projects/Coffice/Sources/App/Entities/TimeOffset.swift
  Projects/Coffice/Sources/App/Entities/User.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Network/Sources/CoreNetwork.swift
  Projects/Network/Sources/DTOs/LoginRequestDTO.swift
  Projects/Network/Sources/DTOs/Requests/LoginRequestDTO.swift
  Projects/Network/Sources/DTOs/Requests/SearchPlaceRequestDTO.swift
  Projects/Network/Sources/DTOs/Responses/Coordinate+AddressDTO.swift
  Projects/Network/Sources/DTOs/Responses/LoginResponseDTO.swift
  Projects/Network/Sources/DTOs/Responses/MemberResponseDTO.swift
  Projects/Network/Sources/DTOs/Responses/PlaceResponseDTO.swift
  Projects/Network/Sources/DTOs/Responses/SearchPlaceResponseDTO.swift
  Projects/Network/Sources/DTOs/Responses/SearchWordResponseDTO.swift
  Projects/Network/Sources/KeyChainManager.swift
  Projects/Network/Sources/NetworkResult.swift
  Tuist/Dependencies.swift
Labels: Feature

#88 Feature/#25 textfield binding example
  Projects/Coffice/Sources/App/Main/MyPage/DevTestCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/DevTestView.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
Labels: Feature, Chore

#97 Feature/#94 bookmark view 제작
  Projects/Coffice/Resources/Colors.xcassets/grayScale8.colorset/Contents.json
  Projects/Coffice/Sources/App/Dependencies/BookmarkAPIClient.swift
  Projects/Coffice/Sources/App/Entities/Address.swift
  Projects/Coffice/Sources/App/Entities/Cafe.swift
  Projects/Coffice/Sources/App/Entities/CrowdednessResponse.swift
  Projects/Coffice/Sources/App/Entities/TimeOffset.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListScreenCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/SearchScreenCore.swift
  Projects/Network/Sources/DTOs/Requests/SaveToFolderRequestDTO.swift
  Projects/Network/Sources/DTOs/Responses/SearchPlaceResponseDTO.swift
Labels: Feature

#92 [Fix] #91 리뷰 작성화면 텍스트 뷰 편집 시 편집 사용성 개선
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewTextView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/KeyboardPresentationReadable.swift
Labels: Fix, Chore

#100 [Fix] #95 개발자 테스트화면 TextField 바인딩 이벤트 2번씩 발생하는 문제 수정
  Projects/Coffice/Sources/App/Main/MyPage/DevTestView.swift
Labels: Fix

#98 [Feat] #93 cafe search view
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/close-circle-fill-18px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/close-circle-fill-18px.imageset/close-circle-fill-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/close-circle-fill-18px.imageset/close-circle-fill@2x-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/close-circle-fill-18px.imageset/close-circle-fill@3x-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/close-24px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/close-24px.imageset/close-24px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/close-24px.imageset/close@2x-24px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/close-24px.imageset/close@3x-24px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/list-24px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/list-24px.imageset/list-24px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/list-24px.imageset/list@2x-24px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/list-24px.imageset/list@3x-24px.png
  Projects/Coffice/Sources/App/AppDelegate.swift
  Projects/Coffice/Sources/App/Dependencies/SearchWordAPIClient.swift
  Projects/Coffice/Sources/App/Entities/RecentSearchWord.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
  Projects/Coffice/Sources/App/Main/Search/CardView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
  Projects/Coffice/Sources/Fonts.swift
  Projects/Network/Sources/DTOs/Responses/SearchWordResponseDTO.swift
Labels: Feature

#103 Feature/#102 naver map add actions
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/marker-unselected-24px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/marker-unselected-24px.imageset/marker-unselected.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/marker-unselected-24px.imageset/marker-unselected@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-24px/marker-unselected-24px.imageset/marker-unselected@3x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36-47px/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36-47px/marker-selected-36-47px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36-47px/marker-selected-36-47px.imageset/marker-selected-36-47px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36-47px/marker-selected-36-47px.imageset/marker-selected@2x-36-47px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36-47px/marker-selected-36-47px.imageset/marker-selected@3x-36-47px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36px/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36px/bookmark-unselected-36px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36px/bookmark-unselected-36px.imageset/bookmark-unselected-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36px/bookmark-unselected-36px.imageset/bookmark-unselected@2x-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-36px/bookmark-unselected-36px.imageset/bookmark-unselected@3x-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-48-52px/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-48-52px/bookmark-selected-48-52px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-48-52px/bookmark-selected-48-52px.imageset/bookmark-selected-48-52px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-48-52px/bookmark-selected-48-52px.imageset/bookmark-selected@2x-48-52px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-48-52px/bookmark-selected-48-52px.imageset/bookmark-selected@3x-48-52px.png
  Projects/Coffice/Sources/App/Entities/Cafe.swift
  Projects/Coffice/Sources/App/Entities/CafeMarkerData.swift
  Projects/Coffice/Sources/App/Entities/MapMarker.swift
  Projects/Coffice/Sources/App/Entities/MapMarkerType.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
  Projects/Network/Sources/DTOs/Responses/SearchPlaceResponseDTO.swift
Labels: Feature

#107 [Fix] #106 카페 검색 상세화면 스크롤영역 하단 일부가 잘리는 현상 수정
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
Labels: Fix

#105 [Feat] #90 필터 바텀시트 UI 및 초기화, 저장 이벤트 구성
  Projects/Coffice/Sources/App/Extensions/Collection+Extensions.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/FilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
Labels: Feature

#109 Feature/#104 my page UI+login flow
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/apple-logo-18px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/apple-logo-18px.imageset/apple-logo-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/apple-logo-18px.imageset/apple-logo@2x-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/apple-logo-18px.imageset/apple-logo@3x-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-18px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-18px.imageset/kakao-logo-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-18px.imageset/kakao-logo@2x-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-18px.imageset/kakao-logo@3x-18px.png
  Projects/Coffice/Resources/Colors.xcassets/secondary0.colorset/Contents.json
  Projects/Coffice/Sources/App/AppCoordinatorCore.swift
  Projects/Coffice/Sources/App/AppDelegate.swift
  Projects/Coffice/Sources/App/Login/LoginType.swift
  Projects/Coffice/Sources/App/Login/LoginView.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Contact/ContactCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/Contact/ContactView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageScreenCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/DevTest/DevTestCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/DevTest/DevTestView.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
  Projects/Coffice/Sources/App/Main/MyPage/LocationServiceTerms/LocationServiceTermsCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/LocationServiceTerms/LocationServiceTermsView.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
  Projects/Coffice/Sources/App/Main/MyPage/PrivacyPolicy/PrivacyPolicyCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/PrivacyPolicy/PrivacyPolicyView.swift
Labels: Feature

#111 Feature/#110 맵뷰 북마크 동작 개선
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/bookmark-unselected-20px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/bookmark-unselected-20px.imageset/bookmark-unselected-20px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/bookmark-unselected-20px.imageset/bookmark-unselected@2x-20px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/bookmark-unselected-20px.imageset/bookmark-unselected@3x-20px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/unselected-20px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/unselected-20px@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/unselected-20px@3x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/bookmark-selected-28-36px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/bookmark-selected-28-36px.imageset/bookmark-selected-28-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/bookmark-selected-28-36px.imageset/bookmark-selected@2x-28-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/bookmark-selected-28-36px.imageset/bookmark-selected@3x-28-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/selected-28-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/selected-28-36px@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/selected-28-36px@3x.png
  Projects/Coffice/Sources/App/Entities/MapMarkerType.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
  Projects/Coffice/Sources/Fonts.swift
Labels: Feature

#113 Feature/#37 filter menu setting
  Projects/Coffice/Sources/App/Extensions/Array+Extensions.swift
  Projects/Coffice/Sources/App/Extensions/Collection+Extensions.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
Labels: Feature, Refactor

#114 [Chore] #37 검색 메인화면 상단에 필터뷰 UI, 이벤트 연결
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#118 [Feat] #115 #116 카페상세 테스트용 진입점 수정, 말풍선 가이드 메세지 표출 로직 구성 (#37 PR merge 선행 필요)
  Projects/Coffice/Sources/App/Main/BubbleMessageCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
  Projects/Coffice/Sources/App/PreferenceKeys/TabBarSizePreferenceKey.swift
Labels: Feature, Test

#117 [Feat] #77 infinite scroll 구현
  Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
  Projects/Coffice/Sources/App/Entities/Address.swift
  Projects/Coffice/Sources/App/Entities/Cafe.swift
  Projects/Coffice/Sources/App/Entities/CafeFilters.swift
  Projects/Coffice/Sources/App/Entities/CafeSearchResponse.swift
  Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCellView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
  Projects/Network/Sources/CoreNetwork.swift
  Projects/Network/Sources/DTOs/Requests/SearchPlaceRequestDTO.swift
  Projects/Network/Sources/DTOs/Responses/Coordinate+AddressDTO.swift
Labels: Feature

#120 [UI] #119 카페 상세화면 UI 디자인가이드 적용
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
  Projects/Coffice/Sources/Fonts.swift
Labels: Feature

#123 [UI] #121 카페 상세, 상단 이미지 페이징 뷰 개발
  Projects/Coffice/Sources/App/Extensions/CofficeImages+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailHeaderView.swift
Labels: Feature

#125 Feature/#124 waypoint+place api
  Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
  Projects/Coffice/Sources/App/Entities/PlaceRequestValue.swift
  Projects/Coffice/Sources/App/Entities/SortDescriptor.swift
  Projects/Coffice/Sources/App/Entities/WayPoint.swift
  Projects/Network/Sources/DTOs/Requests/PlaceRequestDTO.swift
  Projects/Network/Sources/DTOs/Responses/WayPointDTO.swift
Labels: Feature

#130 Feature/#127 운영시간 파싱
  Projects/Coffice/Sources/App/Entities/Cafe.swift
  Projects/Coffice/Sources/App/Entities/OpeningHourResponse.swift
  Projects/Coffice/Sources/App/Entities/OpeningInformation.swift
  Projects/Coffice/Sources/App/Entities/TimeOffset.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCell.swift
Labels: Feature

#136 Feature/#135 review write page
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewTextView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
Labels: Feature, Refactor

#134 Feature/#37 link filter logic in cafesearch
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
Labels: Feature

#142 [Feat] #140 (1/4) 카페 검색 시 필터 설정 적용
  Projects/Coffice/Sources/App/Entities/CafeFilters.swift
  Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Network/Sources/DTOs/Requests/SearchPlaceRequestDTO.swift
Labels: Feature

#141 Feature/#137 커스텀 탭바 구조 수정, 마이페이지 동작연결
  Projects/Coffice/Project.swift
  Projects/Coffice/Sources/App/AppCoordinatorCore.swift
  Projects/Coffice/Sources/App/AppDelegate.swift
  Projects/Coffice/Sources/App/CommonBottomSheet/BottomSheet.swift
  Projects/Coffice/Sources/App/CommonBottomSheet/BottomSheetCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/ToastConfiguration.swift
  Projects/Coffice/Sources/App/Main/ToastView.swift
  Projects/Coffice/Sources/App/TabBar/TabBarCore.swift
  Tuist/Dependencies.swift
Labels: Feature

#144 [Feat] #129 cardView onTapGesture
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#146 Feature/#131 상세화면 맵뷰 추가
  Projects/Coffice/Project.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeDetailNaverMapView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
Labels: Feature

#138 [Feat]/#133 카페 검색 시, waypoint 및 place api 호출 구현 및 역기반 이동
  .swiftlint.yml
  Projects/Coffice/.swiftlint.yml
  Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
  Projects/Coffice/Sources/App/Entities/WayPoint.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
  Projects/Coffice/Sources/App/Main/Search/PlaceCellView.swift
  Projects/Coffice/Sources/App/Main/Search/WaypointCellView.swift
Labels: Feature

#149 [Feat] /#145 ListCellOnTapGesture
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
Labels: Feature

#148 Feature/#139 link review api (get, post)
  Projects/Coffice/Sources/App/Dependencies/ReviewAPIClient.swift
  Projects/Coffice/Sources/App/Entities/GetReviewResponse.swift
  Projects/Coffice/Sources/App/Entities/ReviewUploadRequestValue.swift
  Projects/Coffice/Sources/App/Entities/ReviewsRequestValue.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
  Projects/Network/Sources/DTOs/Requests/ReviewUploadRequestDTO.swift
  Projects/Network/Sources/DTOs/Requests/ReviewsRequestDTO.swift
  Projects/Network/Sources/DTOs/Responses/ReviewResponseDTO.swift
Labels: Feature

#152 [Feat] #150 placeCell, waypointCell onTapGesture 추가
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
Labels: Feature

#154 [Feat] 리뷰 수정, 삭제, 신고 API 인터페이스 구성
  Projects/Coffice/Sources/App/Dependencies/ReviewAPIClient.swift
  Projects/Coffice/Sources/App/Entities/ReviewEditRequestValue.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Network/Sources/DTOs/Requests/ReviewEditRequestDTO.swift
  Projects/Network/Sources/HTTPMethod.swift
Labels: Feature

#155 [Feat] #153 문의하기 화면 개발
  Projects/Coffice/Resources/DeviceModels.json
  Projects/Coffice/Sources/App/Extensions/Bundle+Extensions.swift
  Projects/Coffice/Sources/App/Extensions/UIDevice+Extensions.swift
  Projects/Coffice/Sources/App/Main/MyPage/Contact/ContactCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/Contact/ContactEmailView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Contact/ContactEmailViewState.swift
  Projects/Coffice/Sources/App/Main/MyPage/Contact/ContactView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageScreenCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
Labels: Feature

#160 [Feat]/#140 search place by filter
  Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
Labels: Feature

#162 [Feat] 카페 상세 > 리뷰 목록 관련 팝업 (신고, 수정, 삭제) 표출로직 구성
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteCore.swift
Labels: Feature

#169 [Feat] #168 reset cafe filter
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterInformation.swift
Labels: Feature

#164 [Feat] #163 attributed string 적용
  Projects/Coffice/Sources/App/Extensions/String+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/PlaceCellView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/WaypointCellView.swift
Labels: Feature

#174 [Feat] #171 카페 상세, 리뷰 작성화면 뒤로가기 확인 팝업 UI 표출로직 추가
  Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
Labels: Feature

#167 [Feat] #139 #161 리뷰 삭제 팝업 UI, 삭제 기능 추가
  Projects/Coffice/Sources/App/CommonComponents/Toast/ToastView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
Labels: Feature

#166 [Chore] #165 검색 상세 버튼 제거
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/SearchCoordinatorCore.swift
Labels: Chore

#173 [Feat] #172 nickname UI
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
Labels: Feature

#179 Feature/#178 닉네임 검사 로직 제작
  Projects/Coffice/Sources/App/Dependencies/CheckNicknameAPIClient.swift
  Projects/Coffice/Sources/App/Entities/CheckNicknameResponse.swift
  Projects/Network/Sources/CoreNetwork.swift
  Projects/Network/Sources/DTOs/Requests/CheckNicknameRequestDTO.swift
  Projects/Network/Sources/NetworkResult.swift
Labels: Feature

#184 [Fix] #183 검색 플로우 수정
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchCore.swift
Labels: Fix

#182 [Refactor] 필터 바텀 시트 뷰, 카페 상세화면을 통한 말풍선 뷰 표출방식 수정
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
Labels: Feature, Refactor

#187 Feature/#185#186 cafe detail api link
  Projects/Coffice/Sources/App/Entities/OpeningInformation.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
Labels: Feature

#191 Feature/#190 필터 bottom sheet 표출 및 필터 설정 로직 개선 (PopupView Library 적용)
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
Labels: Refactor

#192 [Feat] #188 카페 검색결과리스트 셀 bookmark API 기능연동
  Projects/Coffice/Sources/App/Entities/Cafe.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapCore.swift
Labels: Feature

#199 [Feat] #158 검색결과 없을 시, ToastView 추가
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#198 Feature/#197 로그아웃, 회원탈퇴 기능 연결
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-fill-18px.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-fill-18px.imageset/kakao-logo-fill-18px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-fill-18px.imageset/kakao-logo-fill-18px@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-18px/kakao-logo-fill-18px.imageset/kakao-logo-fill-18px@3x.png
  Projects/Coffice/Sources/App/AppCoordinatorCore.swift
  Projects/Coffice/Sources/App/Dependencies/AccountClient.swift
  Projects/Coffice/Sources/App/Login/LoginCore.swift
  Projects/Coffice/Sources/App/Login/LoginType.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#200 Feature/#193 login terms bottom sheet (#197 merge 선행 필요)
  Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
  Projects/Coffice/Sources/App/Login/LoginCore.swift
  Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
  Projects/Coffice/Sources/App/Login/LoginServiceTermsSheetCore.swift
  Projects/Coffice/Sources/App/Login/LoginView.swift
Labels: Feature

#202 Feature/#201 login terms of use modal view
  Projects/Coffice/Sources/App/CommonComponents/CommonWebView.swift
  Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
  Projects/Coffice/Sources/App/Login/LoginServiceTermsSheetCore.swift
Labels: Feature

#206 [Fix] Color Asset IPhone -> universal로 수정
  Projects/Coffice/Resources/Colors.xcassets/grayScale1.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale10.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale2.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale3.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale4.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale5.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale6.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale7.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale8.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/grayScale9.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/kakao.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/red.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/secondary0.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/secondary1.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/secondary2.colorset/Contents.json
  Projects/Coffice/Resources/Colors.xcassets/secondary3.colorset/Contents.json
Labels: Fix

#210 [Fix] #208 iOS15version에서 로그인 뷰 깨짐 현상
  Projects/Coffice/Sources/App/Login/LoginView.swift
Labels: Fix

#215 Feature/#214 extend main searchbar touch area
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Fix

#222 [Feat] #221 #186 카페 상세 시간/푸드/음료 정보 표시방식 수정 (#213 선행 merge 필요)
  Projects/Coffice/Sources/App/Entities/ResponseValue/GetReviewResponse.swift
  Projects/Coffice/Sources/App/Extensions/String+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
Labels: Feature, Fix

#224 Feature/#223 recent search keyword title hiding logic
  Projects/Coffice/Sources/App/Extensions/View+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
  Projects/Coffice/Sources/App/ViewModifier/HiddenViewModifier.swift
Labels: Feature

#219 Feature/#204 cafe map view on appear search places
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCore.swift
Labels: Feature

#232 [Feat] #231 카페 토스트 뷰, 리스트 셀 테스트 이미지 제거, placeholder 적용
  Projects/Coffice/Resources/Asset.xcassets/cafe-placeholder.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/cafe-placeholder.imageset/cafe-placeholder.png
  Projects/Coffice/Resources/Asset.xcassets/cafe-placeholder.imageset/cafe-placeholder@2x.png
  Projects/Coffice/Resources/Asset.xcassets/cafe-placeholder.imageset/cafe-placeholder@3x.png
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
Labels: Feature

#233 [Feat] #229 카페 상세화면 url 정보를 통한 웹뷰 표출로직 추가
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
Labels: Feature

#230 [Feat] #186 카페상세 테스트용 이미지 제거, placeholder 적용 및 공유버튼 임시 제거
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
Labels: Feature, Fix

#235 [Fix] #220 최근 검색어 목록 및 검색키워드 입력 시, 표출되는 지하철, 카페 셀 터치 영역 수정
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
Labels: Chore

#234 [Fix] #228 CafeCardView,ListCell 빈 텍스트 UI 수정
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeTagTextView.swift
Labels: Fix

#237 [Feat]/#236 검색어 입력 시, 표출되는 지하철 역 목록과 카페 목록 사이의 회색 가로선 부재(+ 검색 텍스트 필드 폰트 수정)
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
Labels: Feature

#239 [Fix] #238 네비게이션 전환 후, 좌측 swipe 시 pop이 되지 않는 문제 수정
  Projects/Coffice/Sources/App/Extensions/UINavigationController+Extensions.swift
Labels: Feature, Fix

#242 [Chore] #241 CafeDetailView margin 조정
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
Labels: Chore

#248 Feature/#246 cafe detail image placeholder
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-100px/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-100px/ic-placeholder.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-100px/ic-placeholder.imageset/ic-placeholder.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-100px/ic-placeholder.imageset/ic-placeholder@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-100px/ic-placeholder.imageset/ic-placeholder@3x.png
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
Labels: Fix

#249 [Feat] 저장탭 UI 변경, 로그인 플로우 수정
  Projects/Coffice/Sources/App/AppCoordinatorCore.swift
  Projects/Coffice/Sources/App/Login/LoginCore.swift
  Projects/Coffice/Sources/App/Login/LoginView.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/Coordinator+Screen/MyPageCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
Labels: Feature

#251 [Fix] #250 영업시간 하단 시트 필터에서 영업시간보기 필터 버튼 제거
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetViewState.swift
Labels: Fix

#253 [Fix] #252 바텀시트 표출/숨김 애니메이션 속도 수정 (easeOut 0.3 -> 0.2 seconds)
  Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
Labels: Fix

#256 [UI] #255 현위치 재검색 UI 수정
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#261 [Fix] #260 카페상세, 리뷰 작성 상단 UI 이미지 ~ 텍스트 간 간격 수정
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
Labels: Fix

#271 Hotfix/#259 waypoint search word
  Projects/Coffice/Sources/App/Dependencies/SearchWordAPIClient.swift
  Projects/Coffice/Sources/App/Entities/RequestValue/SearchWordUploadRequestValue.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
  Projects/Network/Sources/DTOs/Requests/SearchWordUploadRequestDTO.swift
Labels: Fix

#254 Feature/#240 cafe map popup view
  Projects/Coffice/Sources/App/CommonComponents/ServiceAreaPopup/ServiceAreaPopup.swift
  Projects/Coffice/Sources/App/CommonComponents/ServiceAreaPopup/ServiceAreaPopupView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#281 [Fix] #280 약관동의 하단 시트 아이콘 뿐만아니라 리스트 셀 전체가 터치영역 이어야함
  Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
Labels: Fix

#276 [Feat] #262 review list infinite scroll
  Projects/Coffice/Sources/App/Dependencies/ReviewAPIClient.swift
  Projects/Coffice/Sources/App/Entities/RequestValue/ReviewEditRequestValue.swift
  Projects/Coffice/Sources/App/Entities/RequestValue/ReviewUploadRequestValue.swift
  Projects/Coffice/Sources/App/Entities/RequestValue/ReviewsRequestValue.swift
  Projects/Coffice/Sources/App/Entities/ResponseValue/GetReviewResponse.swift
  Projects/Coffice/Sources/App/Extensions/String+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewTextView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
  Projects/Network/Sources/DTOs/Requests/ReviewEditRequestDTO.swift
  Projects/Network/Sources/DTOs/Requests/ReviewUploadRequestDTO.swift
  Projects/Network/Sources/DTOs/Responses/ReviewResponseDTO.swift
Labels: Feature

#279 Feature/#273 cafe map view filter search
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
Labels: Feature

#287 [Fix] #282, #283 필터 바텀시트 초기화 사양, 설명 메세지뷰 하단 흰띠 보이는 문제 수정
  Projects/Coffice/Sources/App/CommonComponents/BubbleMessage/BubbleMessageView.swift
  Projects/Coffice/Sources/App/Main/MyPage/DevTest/DevTestCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheet.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusCore.swift
Labels: Fix

#286 [Feat] #285 카페 상세의 리뷰 태그, 긍정적인 내용 이외의 ‘콘센트가 적어요’ 같은 값도 보이도록 수정
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewOptionButtonsCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
Labels: Feature

#289 [Fix] #288 리뷰 목록의 하단 구분선이 없도록 수정
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
Labels: Fix

#290 Feature/#278 맵뷰 동작 개선
  Projects/Coffice/Sources/App/Entities/OpeningInformation.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
Labels: Feature

#292 [feat] #291 이모지 변경
  Projects/Coffice/Sources/App/Entities/Cafe/CapacityLevel.swift
Labels: Feature

#296 [Chore] #295 맵핀, 실패 이미지 에셋 변경
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/unselected-20px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/unselected-20px@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-20px/unselected-20px.imageset/unselected-20px@3x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/selected-28-36px.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/selected-28-36px@2x.png
  Projects/Coffice/Resources/Asset.xcassets/CofficeImages-28-36px/selected-28-36px.imageset/selected-28-36px@3x.png
  Projects/Coffice/Resources/Asset.xcassets/saved-list-fail-image-placeholder.imageset/Contents.json
  Projects/Coffice/Resources/Asset.xcassets/saved-list-fail-image-placeholder.imageset/saved-list-fail-image-placeholder.png
  Projects/Coffice/Resources/Asset.xcassets/saved-list-fail-image-placeholder.imageset/saved-list-fail-image-placeholder@2x.png
  Projects/Coffice/Resources/Asset.xcassets/saved-list-fail-image-placeholder.imageset/saved-list-fail-image-placeholder@3x.png
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
Labels: Feature

#298 [Feat] #297 카페상세, 저장리스트 refresh control 적용
  Projects/Coffice/Sources/App/Main/SavedList/SavedListCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
Labels: Feature
