Repository YAPP-Github/Coffice-iOS, pull requests merged in 2023-06, with the labels that each got.

#22 Feature/#21 link google analytics
  .gitignore
  Projects/Cafe/Project.swift
  Projects/Cafe/Sources/AppDelegate.swift
  Projects/Cafe/Sources/CafeApp.swift
  Projects/Cafe/Sources/LoginCore.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Chore

#24 Feature/#15 cafe map view
  .gitignore
  Projects/Cafe/Project.swift
  Projects/Cafe/Sources/CafeApp.swift
  Projects/Cafe/Sources/CafeMapCore.swift
  Projects/Cafe/Sources/LocationManager.swift
  Projects/Cafe/Sources/SavedListScreenCore.swift
  Projects/Cafe/Sources/SearchCoordinatorCore.swift
  Projects/Cafe/Sources/View/CafeMapView.swift
  Projects/Cafe/Sources/View/MarkerView.swift
  Projects/Cafe/Sources/View/NaverMapView.swift
  Projects/Cafe/Sources/View/SearchCoordinatorView.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Xcconfig/dummy
Labels: Feature

#28 #26 #27 마이페이지 일부 필수 메뉴 화면 플로우 구성, 파일 폴더 분류 및 불필요 파일 정리
  Projects/Cafe/Sources/App/AppCoordinatorCore.swift
  Projects/Cafe/Sources/App/AppCoordinatorView.swift
  Projects/Cafe/Sources/App/AppDelegate.swift
  Projects/Cafe/Sources/App/AppScreenCore.swift
  Projects/Cafe/Sources/App/CafeApp.swift
  Projects/Cafe/Sources/App/Dependencies/APIClient.swift
  Projects/Cafe/Sources/App/Dependencies/LocationManager.swift
  Projects/Cafe/Sources/App/Extensions/UIApplication+Extensions.swift
  Projects/Cafe/Sources/App/Extensions/View+Extensions.swift
  Projects/Cafe/Sources/App/Login/LoginCoordinatorCore.swift
  Projects/Cafe/Sources/App/Login/LoginCoordinatorView.swift
  Projects/Cafe/Sources/App/Login/LoginCore.swift
  Projects/Cafe/Sources/App/Login/LoginScreenCore.swift
  Projects/Cafe/Sources/App/Login/LoginView.swift
  Projects/Cafe/Sources/App/Main/Home/HomeCoordinatorCore.swift
  Projects/Cafe/Sources/App/Main/Home/HomeCoordinatorView.swift
  Projects/Cafe/Sources/App/Main/Home/HomeCore.swift
  Projects/Cafe/Sources/App/Main/Home/HomeScreenCore.swift
  Projects/Cafe/Sources/App/Main/Home/HomeView.swift
  Projects/Cafe/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Cafe/Sources/App/Main/MainCoordinatorView.swift
  Projects/Cafe/Sources/App/Main/MyPage/DevTestCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/DevTestView.swift
  Projects/Cafe/Sources/App/Main/MyPage/MyPageCoordinatorCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/MyPageCoordinatorView.swift
  Projects/Cafe/Sources/App/Main/MyPage/MyPageCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/MyPageScreenCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/MyPageView.swift
  Projects/Cafe/Sources/App/Main/MyPage/OpenSourcesCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/OpenSourcesView.swift
  Projects/Cafe/Sources/App/Main/MyPage/PrivacyPolicyCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/PrivacyPolicyView.swift
  Projects/Cafe/Sources/App/Main/MyPage/ServiceTermsCore.swift
  Projects/Cafe/Sources/App/Main/MyPage/ServiceTermsView.swift
  Projects/Cafe/Sources/App/Main/SavedList/SavedListCoordinatorCore.swift
  Projects/Cafe/Sources/App/Main/SavedList/SavedListCoordinatorView.swift
  Projects/Cafe/Sources/App/Main/SavedList/SavedListCore.swift
  Projects/Cafe/Sources/App/Main/SavedList/SavedListScreenCore.swift
  Projects/Cafe/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Cafe/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Cafe/Sources/App/Main/Search/CafeMapView.swift
  Projects/Cafe/Sources/App/Main/Search/MarkerView.swift
  Projects/Cafe/Sources/App/Main/Search/NaverMapView.swift
  Projects/Cafe/Sources/App/Main/Search/SearchCoordinatorCore.swift
  Projects/Cafe/Sources/App/Main/Search/SearchCoordinatorView.swift
  Projects/Cafe/Sources/App/Main/Search/SearchScreenCore.swift
  Projects/Cafe/Sources/App/TabBarCore.swift
  Projects/Cafe/Sources/App/TabBarView.swift
  Projects/Cafe/Sources/App/ViewModifier/CustomNavigationBarModifier.swift
  Projects/Cafe/Sources/MyPageCore.swift
  Projects/Cafe/Sources/SavedListCore.swift
  Projects/Cafe/Sources/View/SearchView.swift
Labels: Feature, Chore

#34 #32 검색 메인화면 상단 검색바, 필터뷰 기본 UI 구성
  Projects/Cafe/Sources/App/AppCoordinatorView.swift
  Projects/Cafe/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Cafe/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#55 [UI] #51 카페 검색결과 상세페이지 파일 추가 및 헤더, 메뉴화면 기본 구조 구정
  Projects/Coffice/Project.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListScreenCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorView.swift
Labels: Feature

#63 [UI] 카페 카드뷰 제작
  Projects/Coffice/Sources/App/Extensions/View+Extensions.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/ViewModifier/RoundedCornerViewModifier.swift
Labels: Feature

#62 Feature/#56 book mark api client
  Projects/Coffice/Sources/App/Dependencies/BookmarkAPIClient.swift
  Projects/Network/Sources/DTOs/PlaceResponseDTO.swift
  Projects/Network/Sources/DTOs/SearchPlaceResponseDTO.swift
Labels: Feature

#57 [Feat] #50 플로팅 버튼 api 연동 및 로직 구현
  Projects/Coffice/Sources/App/Dependencies/LocationManager.swift
  Projects/Coffice/Sources/App/Entities/CafeMarkerData.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CustomInfoWindowView.swift
  Projects/Coffice/Sources/App/Main/Search/MarkerView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
Labels: Feature

#61 [UI] 카페 상세 화면 UI 구성 (상단 메인 화면, 하단 상세정보 및 리뷰 메뉴 화면)
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailSubInfoView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailView.swift
Labels: Feature

#68 [UI] #51 카페 검색결과 상세페이지 말풍선 UI 개발
  Projects/Coffice/Sources/App/Extensions/CofficeImages+Extensions.swift
  Projects/Coffice/Sources/App/Main/BubbleMessageCore.swift
  Projects/Coffice/Sources/App/Main/BubbleMessageView.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchDetailSubInfoView.swift
Labels: Feature

#69 [UI] filter bottom sheet 제작
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListScreenCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/FilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorView.swift
Labels: Feature

#71 Feature/#65 marker 제작 및 메모리 누수 해결
  Projects/Coffice/Sources/App/Dependencies/APIClient.swift
  Projects/Coffice/Sources/App/Dependencies/SearchWordAPIClient.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailSubInfoView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
Labels: Feature

#76 [UI] #70 card view redesign
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/PreferenceKeys/TabBarSizePreferenceKey.swift
  Projects/Coffice/Sources/App/TabBarView.swift
Labels: Feature

#80 [Feat] #79 매장 검색 api 연동
  Projects/Coffice/Sources/App/Dependencies/SearchPlaceAPIClient.swift
  Projects/Coffice/Sources/App/Entities/SearchPlaceRequestValue.swift
  Projects/Network/Sources/DTOs/SearchPlaceRequestDTO.swift
Labels: Feature

#78 [UI] #75 review write UI
  Projects/Coffice/Sources/App/Main/SavedList/SavedListScreenCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/CafeSearchDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewOptionButtonsView.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteCore.swift
  Projects/Coffice/Sources/App/Main/Search/Detail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/Search/SearchCoordinatorView.swift
Labels: Feature
