Repository YAPP-Github/Coffice-iOS, pull requests merged in 2023-10, with the labels that each got.

#324 [Fix] #323 저장리스트 목록이 스크롤 가능할 정도로 많을 경우 하단 정보가 잘려보이는 현상 수정
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
Labels: Fix

#326 [Fix] #319 thumbnail, placeholder image 사양 수정 후 저장리스트목록 모서리 레이아웃 사양 수정
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
Labels: Fix

#328 [Fix] #327 - 프로필 편집화면 > swipe로 뒤로가기 시 마이페이지에서 탭바가 사라지지 않도록 수정
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
Labels: Fix

#330 Feature/#329 fix lint error
  Projects/Coffice/Sources/App/CommonComponents/BubbleMessage/BubbleMessageView.swift
  Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
  Projects/Coffice/Sources/App/CommonComponents/ServiceAreaPopup/ServiceAreaPopupView.swift
  Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
  Projects/Coffice/Sources/App/Login/LoginView.swift
  Projects/Coffice/Sources/App/Main/Home/HomeView.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/MyPage/AppServiceTerms/AppServiceTermsView.swift
  Projects/Coffice/Sources/App/Main/MyPage/DevTest/DevTestView.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
  Projects/Coffice/Sources/App/Main/MyPage/LocationServiceTerms/LocationServiceTermsView.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
  Projects/Coffice/Sources/App/Main/MyPage/PrivacyPolicy/PrivacyPolicyView.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewOptionButtonsView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
  Projects/Coffice/Sources/App/TabBar/TabBarView.swift
Labels: Fix

#332 [Feature] 마커 클릭시 bottom의 cardview 애니메이션 추가
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
Labels: Feature

#334 [Fix] #333 - CafeCardView 애니메이션 추가 이후 bottomFloatingButtonView 이 가운데 정도에 위치해있는 버그 디버깅
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
  Projects/Coffice/Sources/App/ViewModifier/IfModifier.swift
Labels: Fix

#337 [Fix] #336 아이패드 > 일부 레이아웃이 SafeArea 없는 기기를 고려하지 않아서 생기는 문제 수정
  Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
  Projects/Coffice/Sources/App/Login/LoginView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
Labels: Fix

#338 [Fix, 스크롤뷰를 적용하지않아 작은화면에서 버튼이 가려지는 이슈 디버깅]
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
Labels: Fix

#339 [Chore] #314 Merge branch 'develop' into 'main'
  Projects/Coffice/Project.swift
  Projects/Coffice/Sources/App/CommonComponents/BubbleMessage/BubbleMessageView.swift
  Projects/Coffice/Sources/App/CommonComponents/CommonBottomSheet/BottomSheet.swift
  Projects/Coffice/Sources/App/CommonComponents/ServiceAreaPopup/ServiceAreaPopupView.swift
  Projects/Coffice/Sources/App/Entities/Cafe/Cafe.swift
  Projects/Coffice/Sources/App/Login/LoginServiceTermsBottomSheetView.swift
  Projects/Coffice/Sources/App/Login/LoginView.swift
  Projects/Coffice/Sources/App/Main/Home/HomeView.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
  Projects/Coffice/Sources/App/Main/MainCoordinatorView.swift
  Projects/Coffice/Sources/App/Main/MyPage/AppServiceTerms/AppServiceTermsView.swift
  Projects/Coffice/Sources/App/Main/MyPage/DevTest/DevTestView.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileCore.swift
  Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
  Projects/Coffice/Sources/App/Main/MyPage/LocationServiceTerms/LocationServiceTermsView.swift
  Projects/Coffice/Sources/App/Main/MyPage/MyPageView.swift
  Projects/Coffice/Sources/App/Main/MyPage/PrivacyPolicy/PrivacyPolicyView.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListCore.swift
  Projects/Coffice/Sources/App/Main/SavedList/SavedListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailHeaderView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailMenuView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailSubInfoView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/CafeDetailView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewOptionButtonsView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/Review/CafeReviewWriteView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeDetail/UserReviewCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterBottomSheet/CafeFilterBottomSheetView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeFilterMenusView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
  Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListCell.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchListView.swift
  Projects/Coffice/Sources/App/Main/Search/CafeSearch/CafeSearchView.swift
  Projects/Coffice/Sources/App/Main/Search/NaverMap/NaverMapView.swift
  Projects/Coffice/Sources/App/TabBar/TabBarCore.swift
  Projects/Coffice/Sources/App/TabBar/TabBarView.swift
  Projects/Coffice/Sources/App/ViewModifier/IfModifier.swift
  README.md
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Release base
